### ISSUE TITLE
Magica Cloth Support

### ISSUE THREAD

**Issue by Wei-1** [pixiv/three-vrm#1008]
Hello All,

I am making a VTuber website: https://openlive3d.com/
I got a request to support "Magica Cloth".
After a bit of research, it seems like "Magica Cloth" doesn't support WebGL.
https://magicasoft.jp/en/magica-cloth-2/

However, the root cause is because Unity Burst compiler didn't compile the job for WebGL by Unity,
while Burst does support WebAssembly as the target.
https://forum.unity.com/threads/burst-for-webgl.1145144/

I think as long as the information is stored in the VRM file,
we might be able to bypass the compiler, as it is loaded by Three-VRM?

I had checked the VRM spec and this repo, and it doesn't seem to state that in the document?

Best Regards,
Wei

**Comment by 0b5vr** [comment]
three-vrm is an implementation of VRM spec for Three.js.

As far as I know, MagicaCloth provides neither any implementations other than Unity's nor its specification.

I'm 90% sure the requester misunderstands something.

**Comment by Wei-1** [comment]
I mean, after the Magica Cloth modification, the VRM file is saved.
We ship the VRM file to another person.
And that person use another tool to open it, such as VSeeFace (based on Unity), and it will still have the Magica Cloth effect.
I believe some data is stored in the VRM file, so the effect is kept?
Let me double confirm with the requester on this for clarification.

**Comment by 0b5vr** [comment]
> I believe some data is stored in the VRM file, so the effect is kept?

definitely not, any data related to magicacloth should not be serialized into VRM files.

**Comment by saturday06** [comment]
> I mean, after the Magica Cloth modification, the VRM file is saved.

VRM does not have the ability to store the Magica Cloth configuration. Maybe the saved file is in a VSFAvatar format. A VSFAvatar format is a Unity AssetBundle, which is not compatible with VRM.

**Comment by Wei-1** [comment]
> VRM does not have the ability to store the Magica Cloth configuration. Maybe the saved file is in a VSFAvatar format. A VSFAvatar format is a Unity AssetBundle, which is not compatible with VRM.

Yeah, it makes sense. The VSeeFace document also stated that it will export the model in VSFAvatar.

Thanks for the help!
I will close this issue.
