### ISSUE TITLE
[1.0 beta 19] Mixamo animation not work after change the mesh of the model

### ISSUE THREAD

**Issue by HaitianLi** [pixiv/three-vrm#1043]
Hi, since that almost all characters are composed by skinnedMesh children and a lot of time is necessary change a part of the character like clothes, hair, face within characters  without broken animation 
Is there a way that could let me change the mesh of a model that does not break the animation? 
This picture shows that the male animation after the change of the bottom dress.
<img width="595" alt="image" src="https://user-images.githubusercontent.com/44156794/190054987-ff31397f-d017-4cd3-9f59-a98e404a4abd.png">
This is what the code looks like, basically, just change the original model's bottom dress with another model's bottom dress.
Is this possible to make it happen?. 
Sometimes it works when I delete some extra bones from the target mesh and change its blindMatrix with the original model, but it actually makes the dress really small and the leg will be outside the dress, Is there a way to avoid this problem or scale the dress?

Thanks a lot for your help!
`    const loader = new THREE.GLTFLoader();

    loader.register((parser) => {return new THREE_VRM.VRMLoaderPlugin( parser, {autoUpdateHumanBones: true } );}); // here we are installing VRMLoaderPlugin
    [loadModel, tempModel] = await Promise.all(
        [
            loader.loadAsync("/static/model/test/newtest.vrm"),
            loader.loadAsync("/static/model/test2/newVrm.vrm")
        ]
    )
    
    
    const vrm1= loadModel.userData.vrm
    const vrm2= tempModel.userData.vrm
    scene.add(vrm1.scene);
    //scene.remove(vrm.scene);

    const tempMesh = vrm2.scene.children[4].children[2];
    
    const oriMesh = vrm1.scene.children[4].children[1];
    
    vrm1.scene.children[4].children[1] = vrm2.scene.children[4].children[2];

    console.log(vrm1.scene.children);
    console.log(vrm2.scene.children);
    currentVrm = vrm1;

    loadFBX( currentAnimationUrl );`

**Comment by 0b5vr** [comment]
You want to replace a part of a model with a part of another model, right?
First, I clarify that that is out-of-scope as a three-vrm feature.

> ```js
> const tempMesh = vrm2.scene.children[4].children[2];
>
> const oriMesh = vrm1.scene.children[4].children[1];
>
> vrm1.scene.children[4].children[1] = vrm2.scene.children[4].children[2];
> ```

This is not how it's supposed to work.
In three.js, the hierarchy must be changed by calling either `Object3D.add` or `Object3D.remove` otherwise.

Once you modify the hierarchy using these methods, you can do the skinning of the source mesh using the destination skeleton using `SkinnedMesh.bind`, if the skeleton structures are identical between the two models you are using.

See the document of SkinnedMesh also: https://threejs.org/docs/#api/en/objects/SkinnedMesh

**Comment by HaitianLi** [comment]
Hi 0b5vr,
Thanks a lot for your quick reply. I have tried multiple ways to replace a part of a model with another part of the model. But none of them works due to the skeleton problem(vrm model with different clothing normally have different skeleton structure), and the skeleton problem nearly cannot be solved in three.js.
But I actually come out with another solution that is copy one mesh from one model to another in the software blender. And use the attribute "visible"(in three.js) of a mesh object to control the dress of a vrm model. And it works! 
<img width="472" alt="image" src="https://user-images.githubusercontent.com/44156794/190558436-f193341f-fe12-4e3c-8f4a-930a205df74f.png">
<img width="447" alt="image" src="https://user-images.githubusercontent.com/44156794/190558459-bb6dd376-3813-488b-bfc8-14cad3eda844.png">
Thanks a lot for your help!
Haitian

**Comment by 0b5vr** [comment]
good!

**Comment by YulesRules** [comment]
@HaitianLi can you talk more about your solution? : ]

**Comment by HaitianLi** [comment]
@YulesRules refer to this part "But I actually come out with another solution that is copy one mesh from one model to another in the software blender. And use the attribute "visible"(in three.js) of a mesh object to control the dress of a vrm model. And it works!". As I remember, u could add all your material(the part you want to change) on the model, and in three.js set them as invisible, and when you trying to change the material(for example the colour/clothing), you could set the previous one to invisible and set the one you wanna change as visible.
