### ISSUE TITLE
Upgrade set-value

### ISSUE THREAD

**Issue by sue445** [pixiv/three-vrm#112]
Security Alert in `yarn.lock` and `playground/yarn.lock` :tired_face:

https://github.com/pixiv/three-vrm/network/alert/yarn.lock/set-value/open

![image](https://user-images.githubusercontent.com/608755/64790742-8d6a6a80-d5b1-11e9-8cc0-e6729e233674.png)

https://github.com/pixiv/three-vrm/network/alert/playground/yarn.lock/set-value/open

![image](https://user-images.githubusercontent.com/608755/64788652-e2a47d00-d5ad-11e9-9344-6251b2b57323.png)

**Comment by 0b5vr** [comment]
Closing stale issues
