### ISSUE TITLE
look left not working

### ISSUE THREAD

**Issue by branaway** [pixiv/three-vrm#1138]
const lookleft = this.vrm.expressionManager.getExpressionTrackName( THREE_VRM.VRMExpressionPresetName.LookLeft );

It would return null.

The model is a custom made by an external artist if it's relevant. 

three-arm 1.0.6 with threejs 146

**Comment by branaway** [comment]
it would return undefined t be precise.

**Comment by tejasnayak25** [comment]
I'm working with something similar. In fact, I have issues setting the look left, look right, surprised, lookup, look down while other expressions are just working fine.

**Comment by branaway** [comment]
I cannot rule out the possibility that the model from VRoid studio is faulty thou.

**Comment by 0b5vr** [comment]
Moving to Discussions since it's an avatar specific issue
