### ISSUE TITLE
`CONTRIBUTING.md` development instructions missing build step

### ISSUE THREAD

**Issue by mattrossman** [pixiv/three-vrm#1190]
I am trying to set up this project for local development.

I read the "How to develop" section in `CONTRIBUTING.md`:

https://github.com/pixiv/three-vrm/blob/57d7bdae4f41009e2ca362852e3e2138b4f5a65a/CONTRIBUTING.md?plain=1#L5-L13

When I run the steps shown and open `http://localhost:10001/examples/` I see the examples page, but when I open one such as `basic.html`, I get an import error in the console:

```
❌ Uncaught TypeError: Failed to resolve module specifier "@pixiv/three-vrm-materials-mtoon". Relative references must start with either "/", "./", or "../".
```

I also see some warnings in the terminal:

<img width="667" alt="image" src="https://user-images.githubusercontent.com/22670878/227563599-5e1e8b4d-b600-4bd3-bdec-68407ce00f90.png">

It seems the instructions should include a `yarn build` step after the initial `yarn` install:

```sh
yarn 
yarn build
cd packages/three-vrm 
yarn dev 
```

That allows me to run the examples properly.

**Comment by 0b5vr** [comment]
That is true, we have to rearrange the yarn scripts.

Thank you for the workaround steps.

**Comment by 0b5vr** [comment]
ahh, I just noticed that simply running `yarn` does not build submodules in the first place. thank you!
