### ISSUE TITLE
Mesh breaking when VRM gets animated

### ISSUE THREAD

**Issue by c4b4d4** [pixiv/three-vrm#1197]
I'm having a problem where the mesh is breaking with animations. Some faces disappear, but only when it gets animated. I've tried multiple animations, and they all behave the same. They disappear the head.

Here is my mesh with an animation applied:

<img src="https://user-images.githubusercontent.com/375183/228910179-7b9f614e-4eac-4ad9-811a-8f9be108c7dc.png" width="250px"/>

At first, I thought it was a problem with "First" and "Third" person view affecting my mesh, but I concluded it has nothin to do with that.

Here is the mesh when is not animated:

<img src="https://user-images.githubusercontent.com/375183/228912802-4ed86026-549f-4889-b876-cf556574732a.png" width="250px"/>

And here is my skeleton setup in Blender:

<img src="https://user-images.githubusercontent.com/375183/228912857-5cc45e67-daa0-4087-8108-d7fdfdcc63f3.png" width="400px"/>

The way I created the skeleton, is by tapping on the VRM-plugin button: **Create VRM Model**

I've also found out that if I move the bone of the head some centimeters, the faces that get hidden change, it covers more faces in certain bone positions.

Here I moved the head bone a little bit, now more faces have disappeared:

<img src="https://user-images.githubusercontent.com/375183/228915671-98d48266-7bd6-41ab-8129-135f40e484f9.png" width="250px"/>

I even tried to use another type of mesh:

<img src="https://user-images.githubusercontent.com/375183/228914217-4fdc52ed-e3c8-47c5-b966-ad8e067aa65a.png" height="150px" style="display:inline-block;"/>

<img src="https://user-images.githubusercontent.com/375183/228914221-da33e55c-cc50-49be-aa05-61145aef93de.png" height="150px" style="display:inline-block;"/>

Anyone have any idea what's going on? Where could the problem come from?

This has never happened to me before, and it does not happen to meshes that I find online.

Here is my VRM file: [avatar.vrm.zip](https://github.com/pixiv/three-vrm/files/11114260/avatar.vrm.zip)

**Comment by 0b5vr** [comment]
I have just tried it on my end and reproduced the issue.

I have loaded it on https://gltf-viewer.donmccurdy.com/, and it renders the model with the head properly.
It's weird...

**Comment by c4b4d4** [comment]
@0b5vr

Did you animate it? It looks good when it has no animation, but it breaks as soon as I load an animation, I'm using FBX animations (downloaded from Mixamo)

The way I'm animating it is with this method: https://github.com/pixiv/three-vrm/blob/dc5770b53f12cec0ceb7126348683705d7397842/packages/three-vrm/examples/humanoidAnimation/loadMixamoAnimation.js

**Comment by 0b5vr** [comment]
Ah! It's because you have `inputMaxValue: 0` for each lookAt rangeMaps!

![image](https://user-images.githubusercontent.com/7824814/230275124-5563b4c0-37c5-4040-95f7-be8abbf1ad41.png)

It causes zero division.
Set random non-zero value to `inputMaxValue` should fix the problem.

It's too unfriendly to not having a warning for this issue, I will add a warning.

**Comment by 0b5vr** [comment]
How did you make these models?

**Comment by c4b4d4** [comment]
> Ah! It's because you have `inputMaxValue: 0` for each lookAt rangeMaps!

Oh, I see! Makes sense. I don't really know what these values are for. What is `rangeMaps` for? And how is the `outputScale` related?

> How did you make these models?

And, I created them using this Blender Add-On -> https://github.com/saturday06/VRM-Addon-for-Blender 🙂

**Comment by 0b5vr** [comment]
This is the spec for rangeMap:
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0/lookAt.md#rangemap

It basically controls how much of the measured angles should be transferred into the bone rotation.

And ah, you are using Blender add-on. Thank you for the information.
I might want to ask the author also to add a warning on the Blender side later.

**Comment by c4b4d4** [comment]
Great! I'll re-export with non-zero values and test it. I'll close the issue once I've confirmed it 🙂

Thanks for the linking ✨

**Comment by 0b5vr** [comment]
The warning part will be covered in another issue.

**Comment by c4b4d4** [comment]
> Ah! It's because you have `inputMaxValue: 0` for each lookAt rangeMaps!

Confirmed. This was causing the issue.

Thank you 🤝
