### ISSUE TITLE
`uv2_vertex` and `uv2_pars_vertex` failing mtoon VRM rendering in Three v151

### ISSUE THREAD

**Issue by antpb** [pixiv/three-vrm#1198]
In Three.js v151 there were changes that removed `uv2_vertex` and `uv2_pars_vertex` which cause issues loading VRM files that have the mtoon shader.

Here is the Three.js change: https://github.com/mrdoob/three.js/commit/5c5a5c74c6611d3f14dd3e58c5139afd3e4ea182#diff-c2bc4656a48180f106fc5f8813c5d6fd1fe51f8af74b7ac5e1939661379d4841

I found that mtoon uses `uv2_vertex` and `uv2_pars_vertex` in Line 42 and 17 of the mtoon.vert file. 
https://github.com/pixiv/three-vrm/blob/e4a2dcc7de2e0f5801e91afe9b4150982a0b06c4/packages/three-vrm-materials-mtoon/src/shaders/mtoon.vert#L42

I attempted to comment them out, but as expected it broke things further. Reporting here as I try to solve the problem. :)

**Comment by 0b5vr** [comment]
oh no. I will fix this in the next version.

Thank you for the report.

**Comment by 0b5vr** [comment]
r151 support is way harder than I thought; there are many breaking changes on shaderchunks.
Expect more time to support r151.

See:

- https://github.com/mrdoob/three.js/pull/25721
- https://github.com/mrdoob/three.js/pull/25693

**Comment by 0b5vr** [comment]
@antpb `v1.0.10` should fix the shader compilation problem, please try the new version!

https://github.com/pixiv/three-vrm/releases/tag/v1.0.10
