### ISSUE TITLE
Default `shadingShiftTextureScale` to 1

### ISSUE THREAD

**Issue by mattrossman** [pixiv/three-vrm#1248]
The MToon spec indicates that `shadingShiftTextureInfo.scale` should have a default value of "1.0"
<img width="611" alt="CleanShot 2023-07-10 at 12 33 04@2x" src="https://github.com/pixiv/three-vrm/assets/22670878/f33cd67c-3155-44cb-8739-94928d1b2009">

[(source permalink)](https://github.com/vrm-c/vrm-specification/blob/0861a66eb2f2b76835322d775678047d616536b3/specification/VRMC_materials_mtoon-1.0/schema/mtoon.shadingShiftTexture.schema.json)

Here is a sample file with no "scale" define for its shadingShiftTexture:
[shadingShiftTexture-no-scale.vrm.zip](https://github.com/pixiv/three-vrm/files/12004259/shadingShiftTexture-no-scale.vrm.zip)

When I load it with three-vrm [(mtoon demo)](https://pixiv.github.io/three-vrm/packages/three-vrm-materials-mtoon/examples/loader-plugin.html), the `shadingShiftTextureScale` is set to `null` and the rendered view doesn't look as expected.

<img width="482" alt="CleanShot 2023-07-10 at 12 31 24@2x" src="https://github.com/pixiv/three-vrm/assets/22670878/fa514689-e036-40f4-a5fc-b0ff8368bc1e">
<img width="520" alt="CleanShot 2023-07-10 at 12 31 59@2x" src="https://github.com/pixiv/three-vrm/assets/22670878/3225a876-1d8f-41fb-ba19-a9dbbfc907a1">

Manually setting this to 1 produces the expected result:

<img width="536" alt="CleanShot 2023-07-10 at 12 32 11@2x" src="https://github.com/pixiv/three-vrm/assets/22670878/47cc6d9f-5e8b-48a5-9e16-b2c99bf169fd">

**Comment by 0b5vr** [comment]
Indeed! Thank you for pointing this out!

https://github.com/pixiv/three-vrm/blob/3cfe3003a55e2617e9f1767934ac0aaa01c6f775/packages/three-vrm-materials-mtoon/src/MToonMaterial.ts#L422

This is the problematic line. Would you like to send a PR for this?

**Comment by ke456-png** [comment]
Fixed in #1250 .
Thank you.
