### ISSUE TITLE
Spring bones not adapting to model scale

### ISSUE THREAD

**Issue by mattrossman** [pixiv/three-vrm#1265]
Live reproduction:
https://jsfiddle.net/mattrossman/2wtc4mjf/3/

When applying transforms to the model, the scale of colliders and joints don't change. This makes hair look strange when the model is scaled down.

| scale 1  | scale 0.2 |
| ------------- | ------------- |
| <img height="200" alt="" src="https://github.com/pixiv/three-vrm/assets/22670878/f6d1f0fa-ed58-4e8d-91d6-9782bca5112b">  | <img height="200" alt="" src="https://github.com/pixiv/three-vrm/assets/22670878/2254516f-ad21-4915-a129-203b5723b7cf"> |

It sounds as though https://github.com/pixiv/three-vrm/pull/1152 was supposed to fix this, but I experience it on the latest release.

**Comment by 0b5vr** [comment]
Try reading this article: https://github.com/pixiv/three-vrm/blob/dev/docs/spring-bones-on-scaled-models.md !

You might want to change the scale of joints and colliders as well as the model scale.
As the document says at the very bottom, you probably should make `Map` s from joints and colliders to their original scale.

**Comment by mattrossman** [comment]
Thanks and sorry for the false alarm.

For posterity, here's an updated fiddle with the desired behavior, using your recommendation of `Map`s from joints and colliders to their initial params:

https://jsfiddle.net/mattrossman/2wtc4mjf/4/
