### ISSUE TITLE
Transparency issues with materials

### ISSUE THREAD

**Issue by ButzYung** [pixiv/three-vrm#1266]
The `material.transparent` property is sometimes wrongly set to `false` when such material contains transparent texture that should be set to `true` instead. Below is an example with the [official Alicia VRM model](https://3d.nicovideo.jp/works/td32797).

As you can see, the lines between the eye and eyebrow have some weird green see-through.
![_00](https://github.com/pixiv/three-vrm/assets/3256084/696530f3-861f-4dca-aba8-1bba155c3e83)

If I set that `material.transparent` to `true` on console, the problem is gone, but then it creates some render order issues among materials.
![_01](https://github.com/pixiv/three-vrm/assets/3256084/c5a5b6a9-8470-448e-8585-9a4717588565)

A similar issue can be reproduced in the [drag-n-drop exmaple](https://pixiv.github.io/three-vrm/packages/three-vrm/examples/dnd.html) of three-vrm. Those lines are surrounded by some weird white pixels.
![_02](https://github.com/pixiv/three-vrm/assets/3256084/3961ac48-9826-4f70-82db-5d774cb3da71)

Obviously, this is not the only VRM model affected. Some are less noticeable, while some are very notcieable.
ButzYung/SystemAnimatorOnline#22

If my memory is right, I think this problem didn't exist before the v1.0 of three-vrm (though unfortunately I can't test it on my app with that version anymore)

PS: Changing `.alphaTest` or `.alphaToCoverage` (for MSAA) make the see-through issue less noticeable, though obviously this is not the best solution.

**Comment by zzZazzyzz** [comment]
Thank you for addressing this! I eagerly await an update. Love the software so far!

**Comment by ke456-png** [comment]
Thanks for the report!

Fixed in #1272.

**Comment by ButzYung** [comment]
Thanks for fixing this. I hope to see this fix on the next version of three-vrm soon.

**Comment by 0b5vr** [comment]
@ButzYung We've just released the patched version `v2.0.3` . Thank you for the report again!
