### ISSUE TITLE
r3f look at camera implementation.

### ISSUE THREAD

**Issue by Ppint** [pixiv/three-vrm#1292]
how to make vrm look at camera when using r3f? assume that I make vrm into a separate components. I tried the one in docs and it doesn't work

I followed and adapt from this code pen. https://codesandbox.io/s/react-three-fiber-vrm-9ryxq?file=/src/index.tsx

**Comment by Ppint** [comment]
i got it working but the performance is very poor. it is very laggy.

**Comment by yue4u** [comment]
@Ppint Hi! From my perspective lookAt works as intended. Can you elaborate on what's your problem? 

Please note that the dependencies in the example are very old. Try upgrading three, three-vrm, react and r3f to newer versions. You can find migration guide for three-vrm at https://github.com/pixiv/three-vrm/blob/dev/docs/migration-guide-1.0.md

**Comment by Ppint** [comment]
> @Ppint Hi! From my perspective lookAt works as intended. Can you elaborate on what's your problem?
> 
> Please note that the dependencies in the example are very old. Try upgrading three, three-vrm, react and r3f to newer versions. You can find migration guide for three-vrm at https://github.com/pixiv/three-vrm/blob/dev/docs/migration-guide-1.0.md

now i got it working. but useEffect is causing lag and freeze. any idea how to fix it?

**Comment by Ppint** [comment]
also vrm hair would be jerking randomly

**Comment by yue4u** [comment]
@Ppint  Thanks for the replies. However, I don't notice any particular performance issues in the example on my machine. Can you make sure you have hardware acceleration turned on? 

It'll be very helpful if you can share your machine spec and include some video captures of the issue.

**Comment by 0b5vr** [comment]
Closing due to long inactivity.
