### ISSUE TITLE
Alpha Channel in Color Binds ignored

### ISSUE THREAD

**Issue by BMarcelus** [pixiv/three-vrm#1301]
I have VRMs with expressions that change the alpha channel of a material's main color to make certain materials fade in and out.

The VRMExpressionMaterialColorBind's target value, as well as the MToon Material's color only store r,g,b. The alpha channel of the material is stored in .opacity on the material.
When parsing the VRM, the alpha channel of colorbinds needs to be added either as a new type of OpacityBind or on to the ColorBind

**Comment by 0b5vr** [comment]
Thank you for the report!
Yes, it seems that we don't have alpha binding right now and we have to fix this :bow:
