### ISSUE TITLE
Cloning a VRM

### ISSUE THREAD

**Issue by Samsy** [pixiv/three-vrm#1320]
Hello there ! 

Is there a practicable API un-documented to clone a VRM without re-calling the GLTF-Loader ?

Cloning the meshes and skeletons, seems not be enough since there are some managers associated on the userData coming from the GLTFLoader plugin which we can't currently clone  !

Many thanks :)

**Comment by 0b5vr** [comment]
Duplicate of https://github.com/pixiv/three-vrm/discussions/1172 (and you've already commented on the discussion 😳)

**Comment by Samsy** [comment]
Ho, I'm sorry, I completely forgot that there were this discussion open ! 
My apologies
