### ISSUE TITLE
[BUG] Significant performance bottleneck updating `VRMExpressionTextureTransformBind` textures

### ISSUE THREAD

**Issue by mattrossman** [pixiv/three-vrm#1358]
**Operating System**: MacOS
**Affected browsers**: Chrome (Metal backend) and Safari

_Note that this doesn't affect Chrome's OpenGL backend, only the Metal backend. For me, Metal recently became the default. You can choose a specific backend via chrome://flags#use-angle_

When calling `VRM.update()` on an asset that contains texture transform expression binds, I experience a 66-75% drop in FPS. Specifically, this happens during the `VRMExpressionManager.update()` call.

|Browser|With `VRMExpressionManager.update()`| Without `VRMExpressionManager.update()`|
|--|--|--|
|Chrome|<img width="98" alt="CleanShot 2024-01-26 at 11 26 56@2x" src="https://github.com/pixiv/three-vrm/assets/22670878/99c3abbe-fbf0-4278-a530-ccdb1d242c6d">|<img width="103" alt="CleanShot 2024-01-26 at 11 26 35@2x" src="https://github.com/pixiv/three-vrm/assets/22670878/43f49c0c-24dd-4375-9583-4b1df71edf85">|
|Safari|<img width="90" alt="CleanShot 2024-01-26 at 11 28 07@2x" src="https://github.com/pixiv/three-vrm/assets/22670878/c543d97e-fcf3-47ae-b4e8-749499bc6901">|<img width="101" alt="CleanShot 2024-01-26 at 11 27 57@2x" src="https://github.com/pixiv/three-vrm/assets/22670878/108f0a2a-1a97-40a8-a430-a19d980a875f">|

Chrome's performance profiler indicates that there is a significant bottleneck on the `texSubImage2D` call:

<img width="1163" alt="CleanShot 2024-01-26 at 11 32 06@2x" src="https://github.com/pixiv/three-vrm/assets/22670878/33e99819-6e4c-45f3-acc0-2623cf17bb3b">

I narrowed the cause of this down to two lines in the `VRMExpressionTextureTransformBind` implementation where `.needsUpdate = true` is set on the transformed textures.

https://github.com/pixiv/three-vrm/blob/754f12dffe3c0bc946a063d1efe9d78183172e7a/packages/three-vrm-core/src/expressions/VRMExpressionTextureTransformBind.ts#L134

https://github.com/pixiv/three-vrm/blob/754f12dffe3c0bc946a063d1efe9d78183172e7a/packages/three-vrm-core/src/expressions/VRMExpressionTextureTransformBind.ts#L148

These `.needsUpdate` assignments are unnecessary because we are only modifying the `.repeat` and `.offset` vectors of the texture. Notice that this Three.js example freely updates those texture properties without flagging `.needsUpdate`: https://github.com/mrdoob/three.js/blob/02d4c5aa091ea8b6137db5bf1ad38819308246e3/examples/webgl_raycaster_texture.html#L338-L342

Removing these two lines resolves the performance bottleneck without affecting the texture transform behavior.

Demo: https://stackblitz.com/edit/github-otoerm?file=src%2Fmain.ts

https://github.com/pixiv/three-vrm/assets/22670878/47bf20a2-390c-450e-90b8-ff2d73220101

I suggest removing those two `.needsUpdate = true` lines. I can make a PR for this.

**Comment by 0b5vr** [comment]
The patch also improves the DX11 (Default) backend on Windows Chrome (at least on my end)! 👏
