### ISSUE TITLE
Does three-vrm actually use VRMSpringBoneColliderShapeCapsule?

### ISSUE THREAD

**Issue by ButzYung** [pixiv/three-vrm#1391]
I have checked many VRM models, in which most of them use capsule-shaped colliders, but for some unknown reasons when I check the models like the following

`VRM.springBoneManager.colliders.filter(c=>c.shape.constructor.prototype.type!='sphere')`

All of them returns an empty array, which should mean all colliders are treated as sphere.

**Comment by 0b5vr** [comment]
The capsule collider is introduced in VRM 1.0 and there are few VRM 1.0 models in the community yet.
`VRM1_Constraint_Twist_Sample.vrm` in the three-vrm example should have several capsule colliders (7 of them I believe).
