### ISSUE TITLE
playground error / should VRMLookAtHead have original Head ?

### ISSUE THREAD

**Issue by nysd** [pixiv/three-vrm#141]
VRMLookAtHeadからgetHeadPositionが亡くなっており、playgroundでエラーが発生していました。firstPerson.getFirstPersonWorldPosition(_v3B);に置き換えて修正してもよいのですが、
UniVRMだと、VRMLookAtHeadのHeadとVRMFirstPersonのfirstPersonBoneは独立した扱いになっており、three-vrmの方もVRMLookAtHeadはHeadをHumanBodyBonesからとるように戻した方がよいのかと思ったのですが、いかがでしょうか。

以下UniVRMのVRMLookAtHead
```
 void Awake()
        {
            var animator = GetComponent<Animator>();
            if (animator == null)
            {
                Debug.LogWarning("animator is not found");
                return;
            }

            var head = animator.GetBoneTransform(HumanBodyBones.Head);
            if (head == null)
            {
                Debug.LogWarning("head is not found");
                return;
            }

            Head = head;
        }
```

**Comment by FMS-Cat** [comment]
該当箇所の修正は #127 で行っています。

lookAtの起点の件については、UniVRMの開発チームとも議論が必要と考えます。

**Comment by nysd** [comment]
ありがとうございます。PR確認しました。
playground のエラーは解消確認しましたので一旦クローズします。
