### ISSUE TITLE
Model moving down when sitting mixamo animation applied

### ISSUE THREAD

**Issue by DENNKA** [pixiv/three-vrm#1447]
https://pixiv.github.io/three-vrm/packages/three-vrm/examples/humanoidAnimation/index.html
Reproduce:
- Sitting animation (all is ok)
- Load any another (e. g. same)  
  
Model's legs below ground. 
I'm newbie i don't know how to fix it.
![Screenshot](https://github.com/user-attachments/assets/3a0dce3f-b686-4a2a-b475-518f9ca896d7)
[Sitting And Rubbing Arm.zip](https://github.com/user-attachments/files/16367711/Sitting.And.Rubbing.Arm.zip)

**Comment by 0b5vr** [comment]
Reproduced. This is the bug of the example.
