### ISSUE TITLE
Cached texture fail to load

### ISSUE THREAD

**Issue by Benjythebee** [pixiv/three-vrm#1517]
We upgraded to three-vrm@3.1.4 and three@0.169.0. Since then, on localhost, I often get this error when loading a VRM:
![image](https://github.com/user-attachments/assets/92623748-2620-467e-8f95-4abb2b3efb9b)

This forces me to clear my cache and disable threejs's cache with `THREE.Cache.enabled = false` which is not good.

Any ideas?

**Comment by 0b5vr** [comment]
Could you provide a sandbox that reproduces the issue if it's reproducible with [a sample model](https://github.com/vrm-c/vrm-specification/blob/master/samples/VRM1_Constraint_Twist_Sample/vrm/VRM1_Constraint_Twist_Sample.vrm)?

**Comment by Benjythebee** [comment]
I'm closing because I cannot reproduce for some reason. Will re-open when I can do so!
