### ISSUE TITLE
MToon(Transparent) and UniUnlit(Transparent) render problem

### ISSUE THREAD

**Issue by sh-akira** [pixiv/three-vrm#185]
MToonでRender ModeがTransparentの上にUniGLTF/UniUnlitでTransparentなものを重ねたとき、
下のオブジェクトが表示されないようです。

試したモデルはVRoidのまつげとあとから載せた眼鏡のレンズで起きています
VRoid Hub:
https://hub.vroid.com/characters/2832886738310570521/models/1699704241606415818

three-vrm example:
![image](https://user-images.githubusercontent.com/30430584/66097941-5c42f000-e5db-11e9-920c-4ac0e4519f6a.png)

Unity:
![image](https://user-images.githubusercontent.com/30430584/66097952-6c5acf80-e5db-11e9-841b-f21a3b833f92.png)

MToon setting:
![image](https://user-images.githubusercontent.com/30430584/66098039-e25f3680-e5db-11e9-8404-fe26a60138c1.png)

UniUnlit setting:
![image](https://user-images.githubusercontent.com/30430584/66098072-0fabe480-e5dc-11e9-8196-8643ef92c9ba.png)

**Comment by FMS-Cat** [comment]
本issueにつきまして、該当モデルをいただけていないため、検証作業ができません。
メガネのレンズ部分およびアイライン部分につきまして、詳細なマテリアルのプロパティをいただければと思います。

**Comment by FMS-Cat** [comment]
glTFにおいて、 `alphaMode` が `BLEND` となっているマテリアルを扱う場合、デプスバッファを書き込むか否かは実装に委ねられているようです。
Unityではデプスを書き込まない実装となっていますが、Three.jsではデプスを書き込む実装となっているため、このような見た目の際が発生するようです。

Ref: https://github.com/KhronosGroup/glTF/tree/master/specification/2.0/#alpha-coverage
Ref: https://github.com/mrdoob/three.js/issues/13889

Workaroundとしては、メガネのレンズ部分のマテリアルをUnlit/TransparentからTransparentのMToonにすることで対処可能と思います。

three-vrmについては、GLTFのマテリアルを用いる場合にUnityの実装に合わせるような変更はしないため、このissueは対処しないこととします。
ただ一応、Three.js側に本件について再考を請いてみました:

https://github.com/mrdoob/three.js/issues/17706
