### ISSUE TITLE
Use GLTFLoader plugin system to load MToonMaterial

### ISSUE THREAD

**Issue by 0b5vr** [pixiv/three-vrm#329]
https://github.com/mrdoob/three.js/pull/18421

It seems the PR introduces a plugin system for GLTFLoader.
This is definitely one of best solutions for resolving our current mess found at codes of materials loading.

We might want to separate the implementation of materials (MToon) from here at the point

**Comment by FMS-Cat** [comment]
https://github.com/mrdoob/three.js/pull/19144 got merged and shipped in r118! We should consider support the plugin system @ VRM 1.0 support

**Comment by FMS-Cat** [comment]
I've tried the plugin system personally and turns out it is awesome. We should definitely do this

**Comment by torchesburn** [comment]
So did this get done? Its my exact issue atm.

**Comment by 0b5vr** [comment]
Closing stale issues.

@torchesburn Yes, MToon is currently loaded via plugin system in 1.0 beta stream
