### ISSUE TITLE
`Object3D.updateMatrixWorld` will be renamed

### ISSUE THREAD

**Issue by yomotsu** [pixiv/three-vrm#464]
According to https://github.com/mrdoob/three.js/pull/19969
`updateMatrixWorld` will be renamed to `updateWorldMatrix()`.

Since [three-vrm uses `updateMatrixWorld`](https://github.com/pixiv/three-vrm/search?q=updateMatrixWorld&unscoped_q=updateMatrixWorld), it should be renamed too when we support the next version of three.js

I guess...

**Comment by Mugen87** [comment]
Please note that it's not really a rename since `Objec3D.updateWorldMatrix()` has a different implementation. I guess the PR title is a bit misleading.

Besides, `Objec3D.updateMatrixWorld()` will definitely stay around for backwards compatibility reasons.

**Comment by yomotsu** [comment]
Thanks for the notice! I relieved😄
