### ISSUE TITLE
model.humanoid.setPose(model.humanoid.restPose) Bug?

### ISSUE THREAD

**Issue by JLChnToZ** [pixiv/three-vrm#503]
I don't know if is this a bug or I misused this function, when I call `model.humanoid.setPose(model.humanoid.restPose)` to reset the VRM model's pose, the model is getting weird.
![image](https://user-images.githubusercontent.com/4715281/96276226-48f79c80-1005-11eb-8960-2e7595a4aff6.png)

After I dig in the code, I think the reason causing this bug is in here, which the original bone position is added to the pose data passed by the argument, then the position of all bones are doubled: https://github.com/pixiv/three-vrm/blob/1b4aa0a72b7153a6fba5bc575932f7a8dcb807b8/src/vrm/humanoid/VRMHumanoid.ts#L86-L93

If this is not a bug, is there any proper way to reset the model to its initial state?

**Comment by yomotsu** [comment]
Seems you are applying the restpose to the restpose, then the pose going to be double size restpose.
I think you could pass an empty pose to reset to the restpose.

**Comment by JLChnToZ** [comment]
How about using `getPose()` and `setPose()` later for restoring the pose to previous state? Does it mean the pose data from `getPose()` cannot be used directly? I see the `getPose()` contain position data that will double the position too if given to `setPose()`..

**Comment by JLChnToZ** [comment]
Also according the logic I seen from `setPose()` above, if I pass an empty pose `{}` to it, it just do nothing because it depends on what bone keys are provided and ignoring the others.

**Comment by yomotsu** [comment]
@FMS-Cat Sould `getPose()` return a relative pose or absolute?
I think `getPose()` was added later than `setPose()`.

**Comment by yomotsu** [comment]
We may also need `VRMPose` class in the lib

**Comment by FMS-Cat** [comment]
sorry for the late response, gonna investigate today :bow:

**Comment by FMS-Cat** [comment]
whoa, I didn't expected `getPose` returns positions and rotations of each bone without taking a diff from its rest pose. It's not working as intended. I want to fix this.
Let me check whether we have a lot of user of the function or not.

**Comment by FMS-Cat** [comment]
I have roughly looked for usage of `getPose` on GitHub and I could find a sample, it manually removes positions though 😩
I guess I can safely change the behavior. Let me do this.
Thanks a lot for the issue, @JLChnToZ ! Let me notify once it gets updated.
