### ISSUE TITLE
Add additional BlendShapeGroup options

### ISSUE THREAD

**Issue by yeemachine** [pixiv/three-vrm#668]
Is there any way yet to modify additional BlendShapeGroups outside of the standard list (Ex: A,e,I,o,u,joy,blink,blinkR,blinkL etc)?

The reason is that sometimes setting multiple blend shapes may cause weird results. So I would like to modify each separately so they don't clash.

For example, the expression parameters like Joy link both eye and mouth shape forms on the demo three-vrm-girl model and setting both at 1 leads to scary glitches.

Is there a way to manipulate all the facial features independently? (Ex: smile, frown , any other parameter that's animatable from 0-1)

**Comment by 0b5vr** [comment]
I'm sorry for the late response!

I think it's possible to do by using custom BlendShapeGroups.
I'm sure the feature can be used via the `VRMBlendShapeProxy.setValue()` (the `name` can be either preset name or user specified name defined in the VRM).

https://pixiv.github.io/three-vrm/docs/classes/vrmblendshapeproxy.html#setvalue

Does that answer your question?

**Comment by yeemachine** [comment]
Hi! thanks for getting back to me. 

For example, I tried to add the preset Joy to the official example.

```
const s = Math.sin( Math.PI * clock.elapsedTime );
currentVrm.blendShapeProxy.setValue( THREE.VRMSchema.BlendShapePresetName.A, 0.5 + 0.5 * s );
currentVrm.blendShapeProxy.setValue( THREE.VRMSchema.BlendShapePresetName.BlinkL, 0.5 - 0.5 * s );
currentVrm.blendShapeProxy.setValue( THREE.VRMSchema.BlendShapePresetName.Joy, s)
```

This would cause weird glitching as blendshape Joy also controls some of the parameters of A and the Blink blendshapes. 

https://glitch.com/edit/#!/threevrm-blendshape

Does this mean that if I wanted to control each blendshapegroup individually, like (eyebrow raise, smile, eyeshape smile) it would need to be configured on the VRM model itself through Vroid Studio?

**Comment by 0b5vr** [comment]
VRMs exported from VRoid Studio does not have VRM BlendShapeProxies that controls eyebrows or eyes separately.
Also, the specification of VRM also does not specify detailed expression of each emotional BlendShapeProxies (Joy, Fun, Angry, Sorrow).

You probably want to modify your application to make emotional BlendShapeProxies not interfere with other BlendShapeProxies.

**Comment by yeemachine** [comment]
I see. That's definitely what I was afraid of. Hopefully there will be a standard to export those blendshapes separately in the future. Thanks!

**Comment by karim-moon** [comment]
@0b5vr I've been migrating from vrm 0.X to 2.X to use three.js r153

I stucked with VRMBlendShapeProxy.

bofore i use @pixiv/three-vrm 2.X I used like `vrm.blendShapeProxy`.
But after 2.X it seems like there's no blendShapeProxy.
Is there any way to use it?

I want to use `setValue` method of blendShapeProxy

**Comment by epleaner** [comment]
I'm finding the same as @karim-moon  – any ideas?

Edit: found [this](Expressions) migration description around BlendShapeProxy being renamed to Expressions.

**Comment by ke456-png** [comment]
In VRM1.0 (three-vrm 1.0 later), `BlendShapeProxy` renamed to `Expressions`.
We also renamed our BlendShapeProxy APIs to Expressions.

https://github.com/pixiv/three-vrm/blob/dev/docs/migration-guide-1.0.md#expressions-previously-blendshapeproxy
