### ISSUE TITLE
How should I do to make the VRM

### ISSUE THREAD

**Issue by hulihan-start** [pixiv/three-vrm#734]

**Comment by hulihan-start** [comment]
I have viewed the examples in your project, and I also visited https://github.com/rdrgn/three-vrm.
When I use those three VRM model into Unity, it doesn't work and raise as follows:
Exception: invalid magic
UniGLTF.glbImporter.ParseGlbChunks (System.Byte[] bytes) (at Assets/UniGLTF/Runtime/UniGLTF/IO/glbImporter.cs:82)
UniGLTF.ImporterContext.ParseGlb (System.Byte[] bytes) (at Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs:265)
VRM.vrmAssetPostprocessor.ImportVrm (UniGLTF.UnityPath path) (at Assets/VRM/Editor/Format/vrmAssetPostprocessor.cs:43)
VRM.vrmAssetPostprocessor.OnPostprocessAllAssets (System.String[] importedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at Assets/VRM/Editor/Format/vrmAssetPostprocessor.cs:28)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <695d1cc93cca45069c528c15c9fdd749>:0)
UnityEditor.AssetPostprocessingInternal.InvokeMethod (System.Reflection.MethodInfo method, System.Object[] args) (at /Users/bokken/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:789)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at /Users/bokken/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:167)
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)

The other question is that I have noticed the web page: https://rdrgn.github.io/three-vrm/
It can move with the VMD file, I don't know how to open the VMD file.
If I want to move the model by myself, what should I do and learn? As a beginner, thanks for your help!

**Comment by 0b5vr** [comment]
- I'm sorry but `rdrgn/three-vrm` and `pixiv/three-vrm` are different projects.
- We do not cover the support of neither UniVRM (the VRM implementation works on Unity) nor VMD file in this repository.

**Comment by hulihan-start** [comment]
> * I'm sorry but `rdrgn/three-vrm` and `pixiv/three-vrm` are different projects.
> * We do not cover the support of neither UniVRM (the VRM implementation works on Unity) nor VMD file in this repository.

Thanks for your reply...
In my previous thought, I believe these two projects are related. 
BTW, I have studied the examples and I want to know what knowledge is needed if I need to continue further development on three-vrm? I can just let some of the components rotated but I don't any other thing about that...
I'm sorry this is a question asked as a beginner.><

**Comment by 0b5vr** [comment]
I think you should look at the document of Three.js first: https://threejs.org/docs/index.html#manual/en/introduction/Creating-a-scene
