### ISSUE TITLE
Rendering/casting shadows from models.

### ISSUE THREAD

**Issue by yeemachine** [pixiv/three-vrm#802]
Is it possible for VRMs loaded with three-vrm to cast shadows onto a solid? I tried 
`vrm.scene.castShadow = true;`

I don't think that did anything?

**Comment by yeemachine** [comment]
Nevermind, seems to be possible with scene traversing.

**Comment by yjump** [comment]
> Nevermind, seems to be possible with scene traversing.

Hi, I also want to visualize shadows from 3d models, would you mind provide more details about how to implement scene traversing?

@0b5vr thanks a lot if you can provide some useful advice if possible.

**Comment by YulesRules** [comment]
@yjump 

` vrmScene.traverse((child) => {
    if (child.isMesh) {
     child.castShadow = true;
   }
    }
  );`

**Comment by yjump** [comment]
> @yjump
> 
> ` vrmScene.traverse((child) => { if (child.isMesh) { child.castShadow = true; } } );`

Thanks for your solutions. It works when I use three.js to visualize 3D models with casting shadows. However, when I try to use this solution in https://github.com/pixiv/ChatVRM, It leads to anothor issue in the picture
![error](https://github.com/pixiv/three-vrm/assets/26101847/c0cbfc6f-1fc7-4309-8f01-a7aca8b282fd)
I sincerely appreciate it if you can give some useful advice.
