### ISSUE TITLE
Need Help: VRM avatar bone to Mixamo animation on Three.js

### ISSUE THREAD

**Issue by rondoor124** [pixiv/three-vrm#891]
I have mixamo animations, would like to use the VRM model with the mixamo animation.
Do we have solution or example about that?

**Comment by 0b5vr** [comment]
Which three-vrm version are you using?

I have an example but unfortunately it's using 1.0-beta version of three-vrm instead of 0.x, which have a lot of breaking differences:

https://glitch.com/edit/#!/three-vrm-1-sandbox-mixamo

**Comment by rondoor124** [comment]
どうもありがとうございます！
これは非常に役立ちます。

**Comment by rondoor124** [comment]
So I would like to reopen this issue to get help about how to use Mixamo animation.
I download some animations from the mixamo and renamed something on the `mixamoVRMRigMap.js` as like as the animation track name.
I am sure my rename work is correct
But the animation seems broken...
Can you please provide me with a demo that is using the animations from mixamo?
Here are animation files from mixamo and a screenshot video.
Thanks
https://gofile.io/d/4A0ffD

**Comment by 0b5vr** [comment]
How did you export these animations?
You probably want to export your animation using the default Xbot model in "without skin" setting.

![image](https://user-images.githubusercontent.com/7824814/150047226-2dc0c83d-3b4f-4194-b311-bcbaea753721.png)

The working demo: https://glitch.com/edit/#!/sparkly-enshrined-libra?path=main.js%3A29%3A119

**Comment by rondoor124** [comment]
Thanks!

**Comment by jhsul** [comment]
> Which three-vrm version are you using?
> 
> I have an example but unfortunately it's using 1.0-beta version of three-vrm instead of 0.x, which have a lot of breaking differences:
> 
> https://glitch.com/edit/#!/three-vrm-1-sandbox-mixamo

Just so you know this is incredibly helpful to me! Thank you for posting this!!!
