### ISSUE TITLE
Can't find RGBM16Encoding, RGBM7Encoding from three.js exports

### ISSUE THREAD

**Issue by jhsul** [pixiv/three-vrm#928]
I'm currently unable to use this library at all (using npm, bundling with snowpack):
`Uncaught SyntaxError: The requested module '/_snowpack/pkg/three.v0.137.5.js' does not provide an export named 'RGBM16Encoding'`

I see from here that this might have been fixed already:

https://github.com/pixiv/three-vrm/commit/e367fdf60fb6acda18aa57e3f28c16c6c8b2404e

Will this be updated in npm soon?

**Comment by 0b5vr** [comment]
yes yes, I'm going to deploy. Wait a moment.

**Comment by 0b5vr** [comment]
@jhsul It should be deployed!

https://github.com/pixiv/three-vrm/releases/tag/v0.6.10
https://github.com/pixiv/three-vrm/releases/tag/v1.0.0-beta.10

Let me know if you still have problems.

**Comment by jhsul** [comment]
My hero! Thank you so much
