### ISSUE TITLE
Is the center space same with local space (relative space) in spring bone ?

### ISSUE THREAD

**Issue by sknightq** [pixiv/three-vrm#931]
I was trying to understand the [update of springBone](https://github.com/pixiv/three-vrm/blob/dev/packages/three-vrm/src/springbone/VRMSpringBone.ts#L241), but the 'center space' confused me.
I saw the code in the update method, which is updating the transformation of a spring bone in each frame (If my understanding is correct). In that, the center space looks like a local space.
But if the center space is local space, what does the following code do?
```
 // Get bone position in center space
    this._getMatrixWorldToCenter(_matA);
 // And then back to world space ??
    _matA.multiply(this.bone.matrixWorld); 
    this._centerSpacePosition.setFromMatrixPosition(_matA);
```

what's more, 
Does inverse proxy in the center object is just store the inverse of the world matrix?
```
this._center.userData.inverseCacheProxy
```

**Comment by 0b5vr** [comment]
The terminology "center" is confusing indeed.

It's like for setting an origin of the pseudo physics simulation.
Imagine such a hierarchy for example:

```markdown
- Scene
    - MovingPlatform
        - ModelRoot
            - Hips
                - ...
            - Mesh
```

In this hierarchy, without using the `SpringBoneManager.setCenter()`, spring bones of the model will sway along with the `MovingPlatform`.
By setting the center using `SpringBoneManager.setCenter( movingPlatform )`, spring bones will work relative from the `MovingPlatform`, enables us moving `MovingPlatform` independent to the entire spring bone system.

Here is the reference of `SpringBoneManager.setCenter()`:

https://pixiv.github.io/three-vrm/packages/three-vrm/docs/classes/vrmspringbonemanager.html#setcenter

> I saw the code in the update method, which is updating the transformation of a spring bone in each frame (If my understanding is correct). In that, the center space looks like a local space.
> But if the center space is local space, what does the following code do?

What do you mean by "local space" here? I think it cannot be a local space which is a relative space from the bone itself.

> Does inverse proxy in the center object is just store the inverse of the world matrix?

It stores the inverse world matrix of the object `center`, which is usually set by the method `SpringBoneManager.setCenter()` .

**Comment by sknightq** [comment]
@0b5vr Thanks for your patient reply. I got the meaning of 'center space'.
I said the '[local space](https://doc.babylonjs.com/divingDeeper/mesh/transforms/center_origin/position)' is a space for an object to calculate its children object position. The origin of local space is in the center if the object is a cube. And then the children object can get the local coordinate relative to the local origin.

But the inverse proxy still confuses me. I don't understand why to create the inverse proxy. I think I can get the world matrix by the matrixWorld value stored in the center object and get the inverse world matrix by inverting the matrixWorld value. Using the inverse proxy is just for reducing calculation?

By the way, I couldn't figure out what does '[_parentWorldRotation](https://github.com/pixiv/three-vrm/blob/dev/packages/three-vrm/src/springbone/VRMSpringBone.ts#L252)' do in the update method. It looks like an abandoned value, nowhere using it.
```
  if (this.bone.parent) {
    getWorldQuaternionLite(this.bone.parent, this._parentWorldRotation); // this variable
  } else {
    this._parentWorldRotation.copy(IDENTITY_QUATERNION);
  }
```
I had commented above code, and my spring bone still works well.

**Comment by 0b5vr** [comment]
I'm sorry for the late reply :bow:

> Using the inverse proxy is just for reducing calculation?

Yes, that is the purpose. Computing an inverse of mat4 is unbelievably slow.

> I couldn't figure out what does '[_parentWorldRotation](https://github.com/pixiv/three-vrm/blob/dev/packages/three-vrm/src/springbone/VRMSpringBone.ts#L252)' do in the update method. It looks like an abandoned value, nowhere using it.

Mmmmm, it seems not to be used at all......???

**Comment by sknightq** [comment]
@0b5vr Thanks for the reply again, I had achieved this function (update the springBone) in BabylonJS. I will close the issue as soon as possible!
