### ISSUE TITLE
recorded motion capture data

### ISSUE THREAD

**Issue by gordongekko** [pixiv/three-vrm#943]
Hi,
thanks for this amazing work!
I see how to change arm position, etc. of a vrm with math formulas, but is there a way to load realistic motion data capture and to animate the vrm with it? Or is it impossible?
I know I can add motion capture data in another soft like unity but then it'll be a FBX and not a vrm anymore...
Thanks a lot for your answer!
All best

**Comment by 0b5vr** [comment]
Does this issue help you?: https://github.com/pixiv/three-vrm/issues/891

**Comment by beemsoft** [comment]
Hi,
You can use BVH (https://en.wikipedia.org/wiki/Biovision_Hierarchy) for this.
Demo: http://www.beemsoft.nl/vr/src/demo/bar2/index.html
Source code: https://github.com/beemsoft/webxr-handtracking-playground/tree/master/src/demo/bar2

**Comment by gordongekko** [comment]
Thanks for your answers I'll check that!

**Comment by gordongekko** [comment]
Looks both are working! thanks a lot!
