### ISSUE TITLE
mtoon material doesn't export

### ISSUE THREAD

**Issue by metadev26** [pixiv/three-vrm#969]
I have a vrm file that has mtoon material and imported it to the three.js project using VRM loader. But I faced missing material issues when I exported model using gltf exporter.

       ` var vrmScene;
        model.userData.gltfExtensions = { VRM: {} };
        console.log("VRM ModelAAAAAA: ", model);
        await VRM.from(model).then((vrm) => {
          
          vrmScene.userData.gltfExtensions = { VRM: {} };
              vrmScene = vrm.scene;
        });
        const exporter = new Exporter();
        var options = {
          trs: false,
          onlyVisible: true,
          truncateDrawRange: true,
          binary: true,
          forcePowerOfTwoTextures: false,
          maxTextureSize: 1024 || Infinity,
        };
        exporter.parse(
          vrmScene,
          function (result) {
              var output = JSON.stringify(result, null, 2);
              // saveString(output, `${downloadFileName}.vrm`);
              console.log(result)
              saveArrayBuffer(result, `${downloadFileName}.vrm`);
          },
          options
        );`
        
Thank you.  ありがとうございました。

**Comment by 0b5vr** [comment]
Unfortunately, GLTF Exporter does not support exporting VRM extensions.
We have tried implementing VRM Exporter plugin once but it was technically difficult...
