### ISSUE TITLE
How can i use Mixamo Animations in threejs and vroid model?

### ISSUE THREAD

**Issue by wbq9224** [pixiv/three-vrm#971]
Hello guys, I do some animations using mixamo and unity. And how can i play these animations in threejs?
In gltf models, the way to play animations usually like this:
mixer = new THREE.AnimationMixer(gltf.scene)
clip = THREE.AnimationClip.findByName(gltf.animations, 'animation_0');
action = mixer.clipAction(clip)
action.play()
But in vroid models, i dont know how to find animations which i have already maked in mixamo or 3dmax.
Please help.

**Comment by 0b5vr** [comment]
Does this help?: https://github.com/pixiv/three-vrm/issues/891

**Comment by wbq9224** [comment]
> Does this help?: #891

Thank you for your reply!
It seems that that is what i need. But unfortunately I can not open glitch for some reasons. So i cant watch working demo that you privide in glitch. Could you please privide some key point or code here? Or maybe just a little keypoint hint is also helpful!
Thank you!

**Comment by wbq9224** [comment]
> Does this help?: #891

Finaly i use vpn, open glitch and watched the working demo. it's cool.
I noticed that you use fbx loader to load a fbx model with mixamo animations and built  keyframe track by threejs. And then use mixer to apply the keyframe animation to vrm model. It worked. If i download animated mixamo model and then alreay make these animation in vrm by unity, can i find these animation in vrm model directly? In other words,  Is this fbx model and fbx loader necessary?
Forermore, If my skelon animation is just maked by 3dmax or maye, not by mixamo, can i use this method to play?
Thank you again!

**Comment by 0b5vr** [comment]
I'm not sure which format you are using to export your animations.
In the demo, the animation data is contained in the FBX which doesn't have its own meshes, and the FBX is directly retrieved from Mixamo.

The VRM file format itself doesn't have the ability to contain any animations.
I assume you have modified animations taken from Mixamo using Unity and trying to use the animation in Three.js, is this right?
I'm afraid I don't fully understand your intention.

**Comment by wbq9224** [comment]
> I'm not sure which format you are using to export your animations. In the demo, the animation data is contained in the FBX which doesn't have its own meshes, and the FBX is directly retrieved from Mixamo.
> 
> The VRM file format itself doesn't have the ability to contain any animations. I assume you have modified animations taken from Mixamo using Unity and trying to use the animation in Three.js, is this right? I'm afraid I don't fully understand your intention.

Yes. I'm finding animation data in vrm file just like "gltf.animations" in glb model file and then play it by threejs. Now look like vrm file  itself doesnt contain these animation data, and I need to get these animation data by other animated model format. Then mix it to vrm model, right?
By the way, is 1.0-beta version of three-vrm necessary? Now i'm using 0.6.0 and everything seem fine except animation. I try 1.0.0 beta and material seem have a little different. And when i add HemisphereLight to scene, the glsl shader will throw error.
Thank you for your reply again.

**Comment by 0b5vr** [comment]
> and I need to get these animation data by other animated model format. Then mix it to vrm model, right?

Yes, that's right. The demo uses Mixamo FBX but technically any animation format will do the job.

> By the way, is 1.0-beta version of three-vrm necessary? Now i'm using 0.6.0 and everything seem fine except animation.

It's mainly for VRM 1.0, which is the next generation of the VRM specification.
Once VRM 1.0 gets released, we are going to migrate 1.0 soon.

> And when i add HemisphereLight to scene, the glsl shader will throw error.

That is a separate issue, I will investigate later. Thanks for the report!
https://github.com/pixiv/three-vrm/issues/972

**Comment by wbq9224** [comment]
> > and I need to get these animation data by other animated model format. Then mix it to vrm model, right?
> 
> Yes, that's right. The demo uses Mixamo FBX but technically any animation format will do the job.
> 
> > By the way, is 1.0-beta version of three-vrm necessary? Now i'm using 0.6.0 and everything seem fine except animation.
> 
> It's mainly for VRM 1.0, which is the next generation of the VRM specification. Once VRM 1.0 gets released, we are going to migrate 1.0 soon.
> 
> > And when i add HemisphereLight to scene, the glsl shader will throw error.
> 
> That is a separate issue, I will investigate later. Thanks for the report! #972

Thank you for you reply. It almost solved my question. Now the animation seem  worked.
Since the whole animation system ready for vrm 1.0, I have to update my code which is baseed on 0.6.0 vrm  to the latest. And I found some error such as  "THREE.VRMSchema.HumanoidBoneName.Hips" and so on. So I want to ask if any document for the latest update change point or example for 1.0.0-vrm especially for blendshape and bone.  And what time for releaseing 1.0.

**Comment by 0b5vr** [comment]
> I found some error such as "THREE.VRMSchema.HumanoidBoneName.Hips" and so on. So I want to ask if any document for the latest update change point or example for 1.0.0-vrm especially for blendshape and bone.

We have to prepare the migration guide, yes!

Addressing this ad-hoc, about bones and expressions (formerly called blend shape proxies), you can specify bone names and expression names by raw string e.g. `'hips'` `'head'` in three-vrm v1.0.

> And what time for releaseing 1.0.

Since it depends on the release of VRM 1.0 spec, I'm still not sure about the date.

**Comment by wbq9224** [comment]
Thanks！

**Comment by wbq9224** [comment]
Hello, I have to reopen this issue. I use  https://glitch.com/edit/#!/three-vrm-1-sandbox-mixamo demo code to load animation download from mixamo and play the animation onto vrm model, it's worked.
And when I use animation download from different web such as https://actorcore.reallusion.com/actor and do the same work, it's totally not work. I did many work to try to solve the problem and I failed.
I tryed build a new RigMap which can map new animated model rig to vrm rig. I tryed retarget the new animated model to mixamo rigify rig. All these work not useful. So I wonder how can I use diffierent animation(not only from mixamo) to bind vrm model and then play ? Have a general method ?

**Comment by 0b5vr** [comment]
> I tryed build a new RigMap which can map new animated model rig to vrm rig. I tryed retarget the new animated model to mixamo rigify rig. All these work not useful.

How did it failed to work? It appears to me that you have done proper step to make it work properly.

**Comment by wbq9224** [comment]
> > I tryed build a new RigMap which can map new animated model rig to vrm rig. I tryed retarget the new animated model to mixamo rigify rig. All these work not useful.
> 
> How did it failed to work? It appears to me that you have done proper step to make it work properly.

It's disapperaed. I try many diffierent motions model and they all disapperaed. 
Such as https://actorcore.reallusion.com/motion/free?asset=b083-runtoblastb, I built a new rigmap like this:
'CC_Base_Hip': 'hips',
'CC_Base_Waist': 'spine',
'CC_Base_Spine01': 'chest',
'CC_Base_Spine02': 'upperChest',
'CC_Base_NeckTwist01': 'neck',
'CC_Base_Head': 'head',
'CC_Base_L_Clavicle': 'leftShoulder',
'CC_Base_L_Upperarm': 'leftUpperArm',
'CC_Base_L_Forearm': 'leftLowerArm',
'CC_Base_L_Hand': 'leftHand',
'CC_Base_L_Thumb1': 'leftThumbProximal',
'CC_Base_L_Thumb2': 'leftThumbIntermediate',
'CC_Base_L_Thumb3': 'leftThumbDistal',
'CC_Base_L_Index1': 'leftIndexProximal',
'CC_Base_L_Index2': 'leftIndexIntermediate',
'CC_Base_L_Index3': 'leftIndexDistal',
'CC_Base_L_Mid1': 'leftMiddleProximal',
'CC_Base_L_Mid2': 'leftMiddleIntermediate',
'CC_Base_L_Mid3': 'leftMiddleDistal',
'CC_Base_L_Ring1': 'leftRingProximal',
'CC_Base_L_Ring2': 'leftRingIntermediate',
'CC_Base_L_Ring3': 'leftRingDistal',
'CC_Base_L_Pinky1': 'leftLittleProximal',
'CC_Base_L_Pinky2': 'leftLittleIntermediate',
'CC_Base_L_Pinky3': 'leftLittleDistal',
'CC_Base_R_Clavicle': 'rightShoulder',
'CC_Base_R_Upperarm': 'rightUpperArm',
'CC_Base_R_Forearm': 'rightLowerArm',
'CC_Base_R_Hand': 'rightHand',
'CC_Base_R_Pinky1': 'rightLittleProximal',
'CC_Base_R_Pinky2': 'rightLittleIntermediate',
'CC_Base_R_Pinky3': 'rightLittleDistal',
'CC_Base_R_Ring1': 'rightRingProximal',
'CC_Base_R_Ring2': 'rightRingIntermediate',
'CC_Base_R_Ring3': 'rightRingDistal',
'CC_Base_R_Mid1': 'rightMiddleProximal',
'CC_Base_R_Mid2': 'rightMiddleIntermediate',
'CC_Base_R_Mid3': 'rightMiddleDistal',
'CC_Base_R_Index1': 'rightIndexProximal',
'CC_Base_R_Index2': 'rightIndexIntermediate',
'CC_Base_R_Index3': 'rightIndexDistal',
'CC_Base_R_Thumb1': 'rightThumbProximal',
'CC_Base_R_Thumb2': 'rightThumbIntermediate',
'CC_Base_R_Thumb3': 'rightThumbDistal',
'CC_Base_L_Thigh': 'leftUpperLeg',
'CC_Base_L_Calf': 'leftLowerLeg',
'CC_Base_L_Foot': 'leftFoot',
'CC_Base_L_ToeBaseShareBone': 'leftToes',
'CC_Base_R_Thigh': 'rightUpperLeg',
'CC_Base_R_Calf': 'rightLowerLeg',
'CC_Base_R_Foot': 'rightFoot',
'CC_Base_R_ToeBaseShareBone': 'rightToes',
And I use the new animation clip name(not "mixamo.com"). And finally I play this  new animation track, my vrm model is disapperaed : (

**Comment by wbq9224** [comment]
does anybody can help, plz?

**Comment by 0b5vr** [comment]
Could you provide a demo using services like Glitch or CodeSandbox?

**Comment by wbq9224** [comment]
> Could you provide a demo using services like Glitch or CodeSandbox?


Thank you for your kind help!
Here is a live demo, basiclly same with your code https://github.com/pixiv/three-vrm/issues/891.
I just change the animate model, clip name and rigmap. But everything goes to bad :(
https://codesandbox.io/s/optimistic-dan-qlqgsb?file=/main.js

**Comment by 0b5vr** [comment]
It seems that the animation data needs to be retargeted for the VRM you use and that is unfortunately out-of-scope for three-vrm for now.

**Comment by ep5000** [comment]
I have encountered the same issue.  I started creating a CC3 rig map (similar to that posted above by @wbq9224) and while the animation loads and moves the character the animation's motions are offset quite a bit.  Looks like the same issue faced by the following Godot user: https://github.com/smix8/GodotAnimationRetargeting/issues/19

It appears that the CC3 bone strucutre is farily different than that of Mixamo/VRM and thus requires a significant amount of retargeting.

**Comment by ep5000** [comment]
Similar issue trying to use DeepMotion (https://www.deepmotion.com/).  Using the workflow 1) upload VRM to deep motion -> 2) create animation -> 3) Download as FBX -> 4) Import into three-vrm with appropriate rig map, the animation loads and plays some of the animation correctly although the character's torso jumps up and down sporadically.  See the attached videos:

The skeletons between the exported DeepMotion FBX and the MixamoFBX are quite similar (rig map correlates well).  Any thoughts on what may be causing this?  See video clips for an example of what is happening:

**DeepMotion Animation:**
![DeepMotion - VRM](https://user-images.githubusercontent.com/14168215/196648237-eda85534-3a9d-4636-ae4c-e7363ab584e1.gif)

**three-vrm Animation:**
![Three-VRM - Same VRM](https://user-images.githubusercontent.com/14168215/196648780-b86a9115-ced3-49e1-b12e-799b2fd70830.gif)
